/*-*-c++-*-*************************************************************************************************************
* Copyright 2016 - 2022 Inesonic, LLC.
* 
* This file is licensed under two licenses.
*
* Inesonic Commercial License, Version 1:
*   All rights reserved.  Inesonic, LLC retains all rights to this software, including the right to relicense the
*   software in source or binary formats under different terms.  Unauthorized use under the terms of this license is
*   strictly prohibited.
*
* GNU Public License, Version 2:
*   This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public
*   License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later
*   version.
*   
*   This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
*   warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
*   details.
*   
*   You should have received a copy of the GNU General Public License along with this program; if not, write to the Free
*   Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
********************************************************************************************************************//**
* \file
*
* This header defines the \ref Cbe::LinkerNotifier class.
***********************************************************************************************************************/

/* .. sphinx-project inecbe */

#ifndef CBE_LINKER_NOTIFIER_H
#define CBE_LINKER_NOTIFIER_H

#include <QString>
#include <QSharedPointer>

#include "cbe_common.h"

namespace Cbe {
    class Linker;
    class LinkerContext;

    /**
     * Virtual base class that can be used to intercept notifications from a \ref Cbe::Linker class.  The class
     * provides a number of virtual methods you can overload to receive status notifications from the linker.
     */
    class CBE_PUBLIC_API LinkerNotifier {
        friend class Linker;

        public:
            LinkerNotifier();

            virtual ~LinkerNotifier();

            /**
             * Virtual method you can overload to receive notification when the linker is started.  Note that the
             * method may be called from a different thread than the one used to invoke the linker.
             *
             * The default implementation simply returns.
             *
             * \param[in] context The context that is being executed.
             */
            virtual void linkerStarted(QSharedPointer<LinkerContext> context);

            /**
             * Virtual method you can overload to receive notification when the linker has finished.  Note that the
             * method may be called from a different thread than the one used to invoke the linker.
             *
             * The default implementation simply returns.
             *
             * \param[in] context The context that is being executed.
             *
             * \param[in] success Holds true if the linker completed successfully, returns false if an error is
             *                    reported.
             */
            virtual void linkerFinished(QSharedPointer<LinkerContext> context, bool success);

            /**
             * Virtual method you can overload to receive notification of diagnostic messages from the linker.  Note
             * that the method may be called from a different thread than the one used to invoke the linker.
             *
             * The default implementation simply returns.
             *
             * \param[in] context           The context that is being executed.
             *
             * \param[in] diagnosticMessage The diagnostic message generated by the linker.
             */
            virtual void handleLinkerDiagnostic(
                QSharedPointer<LinkerContext> context,
                const QString&                diagnosticMessage
            );

            /**
             * Method you can use to obtain a pointer to the linker instance providing notifications to this class.
             *
             * \return Returns a pointer to the associated /ref Cbe::Linker class.
             */
            Linker* linker() const;

        private:
            Linker* currentLinker;
    };
};

#endif
