/*-*-c++-*-*************************************************************************************************************
* Copyright 2016 - 2022 Inesonic, LLC.
* 
* This file is licensed under two licenses.
*
* Inesonic Commercial License, Version 1:
*   All rights reserved.  Inesonic, LLC retains all rights to this software, including the right to relicense the
*   software in source or binary formats under different terms.  Unauthorized use under the terms of this license is
*   strictly prohibited.
*
* GNU Public License, Version 2:
*   This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public
*   License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later
*   version.
*   
*   This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied
*   warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
*   details.
*   
*   You should have received a copy of the GNU General Public License along with this program; if not, write to the Free
*   Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
********************************************************************************************************************//**
* \file
*
* This header defines the \ref Cbe::CppCompilerNotifier class.
***********************************************************************************************************************/

/* .. sphinx-project inecbe */

#ifndef CBE_CPP_COMPILER_NOTIFIER_H
#define CBE_CPP_COMPILER_NOTIFIER_H

#include <QString>
#include <QSharedPointer>

#include "cbe_common.h"
#include "cbe_cpp_compiler.h"
#include "cbe_cpp_compiler_context.h"
#include "cbe_cpp_compiler_diagnostic.h"
#include "cbe_compiler_notifier.h"

namespace Cbe {
    /**
     * Virtual base class that can be used to intercept notifications from a \ref Cbe::Compiler class.  The class
     * provides a number of virtual methods you can overload to receive status notifications from the compiler.
     */
    class CBE_PUBLIC_API CppCompilerNotifier:public CompilerNotifier {
        public:
            CppCompilerNotifier();

            ~CppCompilerNotifier() override;

            /**
             * Method you can use to obtain a pointer to the compiler instance providing notifications to this class.
             *
             * \return Returns a pointer to the associated /ref Cbe::Compiler class.
             */
            CppCompiler* compiler() const;

            /**
             * Virtual method you can overload to receive notification when the compiler is started.  Note that the
             * method may be called from a different thread than the one used to invoke the compiler.
             *
             * The default implementation simply returns.
             *
             * \param[in] context The compiler context that work has been started on.
             */
            virtual void compilerStarted(QSharedPointer<CppCompilerContext> context);

            /**
             * Virtual method you can overload to receive notification when the compiler has finished.  Note that the
             * method may be called from a different thread than the one used to invoke the compiler.
             *
             * The default implementation simply returns.
             *
             * \param[in] context The compiler context that has just been finished.
             *
             * \param[in] success Holds true if the compiler completed successfully, returns false if an error is
             *                    reported.
             */
            virtual void compilerFinished(QSharedPointer<CppCompilerContext> context, bool success);

            /**
             * Virtual method you can overload to receive notification of diagnostic messages from the compiler.  Note
             * that the method may be called from a different thread than the one used to invoke the compiler.
             *
             * The default implementation simply returns without performing any additional function.
             *
             * \param[in] diagnostic The diagnostic information generated by the compiler.
             */
            virtual void handleCompilerDiagnostic(const CppCompilerDiagnostic& diagnostic);
    };
};

#endif
